// SPDX-FileCopyrightText: 2026 The KeyStone Authors
// SPDX-License-Identifier: GPL-2.0-or-later

use keystone_core::docs;
use pulldown_cmark::{html, Options, Parser};

pub struct HelpSection {
    pub slug: String,
    pub title: String,
    pub markdown: String,
}

pub fn sections() -> Vec<HelpSection> {
    vec![
        HelpSection {
            slug: "metrics".into(),
            title: "Metrics".into(),
            markdown: docs::metrics_markdown(),
        },
        HelpSection {
            slug: "permissions".into(),
            title: "Permissions".into(),
            markdown: docs::permissions_markdown(),
        },
        HelpSection {
            slug: "docker".into(),
            title: "Docker operations".into(),
            markdown: docs::docker_ops_markdown(),
        },
        HelpSection {
            slug: "widgets".into(),
            title: "Dashboard widgets".into(),
            markdown: docs::widgets_markdown(),
        },
        HelpSection {
            slug: "agent-config".into(),
            title: "Agent configuration".into(),
            markdown: docs::agent_config_markdown(),
        },
        HelpSection {
            slug: "server-config".into(),
            title: "Server configuration".into(),
            markdown: docs::server_config_markdown(),
        },
        HelpSection {
            slug: "server-cli".into(),
            title: "Server CLI".into(),
            markdown: format!(
                "<!-- Generated by cargo xtask docs / keystone-core::docs. Do not edit. -->\n\n{}",
                crate::cli::markdown_help()
            ),
        },
    ]
}

pub fn section(slug: &str) -> Option<HelpSection> {
    sections().into_iter().find(|s| s.slug == slug)
}

pub fn markdown_to_html(md: &str) -> String {
    let mut options = Options::empty();
    options.insert(Options::ENABLE_TABLES);
    let parser = Parser::new_ext(md, options);
    let mut html_out = String::new();
    html::push_html(&mut html_out, parser);
    html_out
}

pub fn all_markdown() -> String {
    let mut out = String::from("# KeyStone reference\n\nGenerated from the running types.\n\n");
    for s in sections() {
        out.push_str(&s.markdown);
        out.push('\n');
    }
    out
}
