// SPDX-FileCopyrightText: 2026 The KeyStone Authors
// SPDX-License-Identifier: GPL-2.0-or-later

use utoipa::OpenApi;

use crate::http::{CatalogApi, NodeDashboardApi};

#[derive(OpenApi)]
#[openapi(
    info(title = "KeyStone", version = env!("CARGO_PKG_VERSION")),
    paths(
        crate::http::catalog_api,
        crate::http::dashboard_get,
        crate::http::dashboard_put,
        crate::http::dashboard_delete
    ),
    components(schemas(CatalogApi, NodeDashboardApi))
)]
pub struct ApiDoc;

pub fn spec_json() -> String {
    ApiDoc::openapi()
        .to_pretty_json()
        .unwrap_or_else(|_| "{}".into())
}

pub fn spec_markdown() -> String {
    let spec = ApiDoc::openapi();
    let mut out = String::from(
        "<!-- Generated by cargo xtask docs / keystone-core::docs. Do not edit. -->\n\n# HTTP API\n\n",
    );
    out.push_str(&format!("{} {}\n\n", spec.info.title, spec.info.version));
    out.push_str("| Method | Path | Summary |\n|---|---|---|\n");
    let mut keys: Vec<_> = spec.paths.paths.keys().cloned().collect();
    keys.sort();
    for path in keys {
        if let Some(item) = spec.paths.paths.get(&path) {
            if item.get.is_some() {
                let summary = item
                    .get
                    .as_ref()
                    .and_then(|o| o.summary.clone())
                    .unwrap_or_default();
                out.push_str(&format!("| GET | `{path}` | {summary} |\n"));
            }
            if item.put.is_some() {
                let summary = item
                    .put
                    .as_ref()
                    .and_then(|o| o.summary.clone())
                    .unwrap_or_default();
                out.push_str(&format!("| PUT | `{path}` | {summary} |\n"));
            }
            if item.delete.is_some() {
                let summary = item
                    .delete
                    .as_ref()
                    .and_then(|o| o.summary.clone())
                    .unwrap_or_default();
                out.push_str(&format!("| DELETE | `{path}` | {summary} |\n"));
            }
        }
    }
    out
}
