// SPDX-FileCopyrightText: 2026 The KeyStone Authors
// SPDX-License-Identifier: GPL-2.0-or-later

//! Markdown renderers used by `cargo xtask docs` and the server `/help` page.
//! Both must call these functions so operators never see a different list
//! than the binary implements.

use schemars::schema::{InstanceType, RootSchema, Schema, SchemaObject, SingleOrVec};
use schemars::JsonSchema;
use strum::IntoEnumIterator;

use crate::config::{AgentConfig, ServerConfig};
use crate::docker::DockerOp;
use crate::metrics::{catalog, MetricType, Stability};
use crate::rbac::Permission;
use crate::widgets::WidgetKind;

const GENERATED_BANNER: &str =
    "<!-- Generated by cargo xtask docs / keystone-core::docs. Do not edit. -->\n\n";

pub fn metrics_markdown() -> String {
    let mut out = String::from(GENERATED_BANNER);
    out.push_str("# Metrics catalog\n\n");
    out.push_str("Unknown names are dropped at ingest. This table is the allowlist.\n\n");
    out.push_str("| Name | Type | Unit | Stability | Labels | Help |\n");
    out.push_str("|---|---|---|---|---|---|\n");
    for def in catalog() {
        let ty = match def.metric_type {
            MetricType::Counter => "counter",
            MetricType::Gauge => "gauge",
        };
        let stab = match def.stability {
            Stability::Stable => "stable",
            Stability::Experimental => "experimental",
        };
        let labels = if def.labels.is_empty() {
            "—".into()
        } else {
            def.labels.join(", ")
        };
        out.push_str(&format!(
            "| `{}` | {} | {} | {} | {} | {} |\n",
            def.name, ty, def.unit, stab, labels, def.help
        ));
    }
    out
}

pub fn permissions_markdown() -> String {
    let mut out = String::from(GENERATED_BANNER);
    out.push_str("# Permissions\n\n");
    out.push_str("The ingest token is not a permission and cannot grant Docker manage.\n\n");
    out.push_str("| Permission | Description |\n|---|---|\n");
    for p in Permission::iter() {
        out.push_str(&format!("| `{}` | {} |\n", p.as_str(), p.description()));
    }
    out
}

pub fn docker_ops_markdown() -> String {
    let mut out = String::from(GENERATED_BANNER);
    out.push_str("# Docker operations\n\n");
    out.push_str(
        "The agent talks to Docker Engine. The server never opens a remote `docker.sock`.\n",
    );
    out.push_str("`docker.manage` is opt-in. Socket access is root-equivalent on that node.\n\n");
    out.push_str("| Operation | Mutating | Permission | Description |\n|---|---|---|---|\n");
    for op in DockerOp::iter() {
        out.push_str(&format!(
            "| `{}` | {} | `{}` | {} |\n",
            op.as_str(),
            if op.mutating() { "yes" } else { "no" },
            op.permission().as_str(),
            op.description()
        ));
    }
    out
}

pub fn widgets_markdown() -> String {
    let mut out = String::from(GENERATED_BANNER);
    out.push_str("# Dashboard widgets\n\n");
    out.push_str(
        "The node overview is a list of widgets, not a hard-coded page. Add a `WidgetKind` variant, hydrate it, and draw it in `app.js`. Layout JSON is stored per node when customised; otherwise the built-in default is used.\n\n",
    );
    out.push_str("| Kind | Description |\n|---|---|\n");
    for k in WidgetKind::iter() {
        out.push_str(&format!("| `{}` | {} |\n", k.as_str(), k.description()));
    }
    out
}

pub fn agent_config_schema() -> RootSchema {
    schemars::schema_for!(AgentConfig)
}

pub fn server_config_schema() -> RootSchema {
    schemars::schema_for!(ServerConfig)
}

pub fn agent_config_markdown() -> String {
    schema_markdown("Agent configuration", &agent_config_schema())
}

pub fn server_config_markdown() -> String {
    schema_markdown("Server configuration", &server_config_schema())
}

fn schema_markdown(title: &str, root: &RootSchema) -> String {
    let mut out = String::from(GENERATED_BANNER);
    out.push_str("# ");
    out.push_str(title);
    out.push_str("\n\nFields come from the Rust config structs (`schemars`).\n\n");
    if let Some(meta) = &root.schema.metadata {
        if let Some(desc) = &meta.description {
            out.push_str(desc);
            out.push_str("\n\n");
        }
    }
    out.push_str("| Field | Type | Description |\n|---|---|---|\n");
    render_object(&mut out, "", &root.schema, root);
    for (name, schema) in &root.definitions {
        if let Schema::Object(obj) = schema {
            out.push_str(&format!("\n## `{name}`\n\n"));
            if let Some(meta) = &obj.metadata {
                if let Some(desc) = &meta.description {
                    out.push_str(desc);
                    out.push_str("\n\n");
                }
            }
            out.push_str("| Field | Type | Description |\n|---|---|---|\n");
            render_object(&mut out, "", obj, root);
        }
    }
    out
}

fn render_object(out: &mut String, prefix: &str, obj: &SchemaObject, root: &RootSchema) {
    let Some(props) = obj.object.as_ref() else {
        return;
    };
    let mut names: Vec<_> = props.properties.keys().cloned().collect();
    names.sort();
    for name in names {
        let schema = &props.properties[&name];
        let field = if prefix.is_empty() {
            name.clone()
        } else {
            format!("{prefix}.{name}")
        };
        match schema {
            Schema::Object(child) => {
                let ty = type_name(child);
                let desc = child
                    .metadata
                    .as_ref()
                    .and_then(|m| m.description.clone())
                    .unwrap_or_default()
                    .replace('\n', " ");
                out.push_str(&format!("| `{field}` | {ty} | {desc} |\n"));
            }
            Schema::Bool(_) => {
                out.push_str(&format!("| `{field}` | unknown |  |\n"));
            }
        }
    }
    let _ = root;
}

fn type_name(obj: &SchemaObject) -> String {
    if let Some(reference) = &obj.reference {
        return reference
            .rsplit('/')
            .next()
            .unwrap_or(reference)
            .to_string();
    }
    if let Some(sub) = &obj.subschemas {
        if let Some(any) = &sub.any_of {
            if any.len() == 2 {
                return format!("optional {}", schema_type_label(&any[0]));
            }
        }
    }
    match &obj.instance_type {
        Some(SingleOrVec::Single(t)) => instance_type_name(**t, obj),
        Some(SingleOrVec::Vec(v)) => v
            .iter()
            .map(|t| instance_type_name(*t, obj))
            .collect::<Vec<_>>()
            .join(" | "),
        None => "object".into(),
    }
}

fn schema_type_label(schema: &Schema) -> String {
    match schema {
        Schema::Object(o) => type_name(o),
        Schema::Bool(_) => "any".into(),
    }
}

fn instance_type_name(t: InstanceType, obj: &SchemaObject) -> String {
    match t {
        InstanceType::String => "string".into(),
        InstanceType::Number => "number".into(),
        InstanceType::Integer => "integer".into(),
        InstanceType::Boolean => "boolean".into(),
        InstanceType::Array => {
            if let Some(arr) = &obj.array {
                if let Some(Schema::Object(item)) = arr.items.as_ref().and_then(|i| match i {
                    schemars::schema::SingleOrVec::Single(s) => Some(s.as_ref()),
                    _ => None,
                }) {
                    return format!("array of {}", type_name(item));
                }
            }
            "array".into()
        }
        InstanceType::Object => "object".into(),
        InstanceType::Null => "null".into(),
    }
}

pub fn json_schema_pretty(schema: &RootSchema) -> String {
    serde_json::to_string_pretty(schema).unwrap_or_else(|_| "{}".into())
}

/// Ensure example configs in the repo still deserialize. Used by tests and xtask.
pub fn parse_example_agent(toml_text: &str) -> Result<AgentConfig, toml::de::Error> {
    toml::from_str(toml_text)
}

pub fn parse_example_server(toml_text: &str) -> Result<ServerConfig, toml::de::Error> {
    toml::from_str(toml_text)
}

// Keep JsonSchema import used (AgentConfig/ServerConfig derive it).
#[allow(dead_code)]
fn _schema_bound<T: JsonSchema>() {}
