// SPDX-FileCopyrightText: 2026 The KeyStone Authors
// SPDX-License-Identifier: GPL-2.0-or-later

//! `cargo xtask docs` regenerates `docs/src/generated/` from runtime types.

use std::path::{Path, PathBuf};

use anyhow::Context;
use keystone_core::docs;

fn main() -> anyhow::Result<()> {
    let args: Vec<String> = std::env::args().skip(1).collect();
    match args.first().map(String::as_str) {
        Some("docs") | None => docs()?,
        Some(other) => anyhow::bail!("unknown xtask {other}; try `cargo xtask docs`"),
    }
    Ok(())
}

fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("..")
}

fn docs() -> anyhow::Result<()> {
    let root = workspace_root();
    let gen = root.join("docs/src/generated");
    std::fs::create_dir_all(&gen)?;
    write(&gen.join("metrics.md"), docs::metrics_markdown())?;
    write(&gen.join("permissions.md"), docs::permissions_markdown())?;
    write(&gen.join("docker-ops.md"), docs::docker_ops_markdown())?;
    write(&gen.join("agent-config.md"), docs::agent_config_markdown())?;
    write(
        &gen.join("server-config.md"),
        docs::server_config_markdown(),
    )?;
    write(
        &gen.join("agent-config.schema.json"),
        docs::json_schema_pretty(&docs::agent_config_schema()),
    )?;
    write(
        &gen.join("server-config.schema.json"),
        docs::json_schema_pretty(&docs::server_config_schema()),
    )?;
    write(
        &gen.join("agent-cli.md"),
        format!(
            "<!-- Generated by cargo xtask docs / keystone-core::docs. Do not edit. -->\n\n{}",
            keystone_agent::cli::markdown_help()
        ),
    )?;
    write(
        &gen.join("server-cli.md"),
        format!(
            "<!-- Generated by cargo xtask docs / keystone-core::docs. Do not edit. -->\n\n{}",
            keystone_server::cli::markdown_help()
        ),
    )?;
    write(
        &gen.join("openapi.md"),
        keystone_server::openapi::spec_markdown(),
    )?;
    write(
        &gen.join("openapi.json"),
        keystone_server::openapi::spec_json(),
    )?;
    println!("wrote {}", gen.display());
    Ok(())
}

fn write(path: &Path, contents: String) -> anyhow::Result<()> {
    std::fs::write(path, contents).with_context(|| format!("write {}", path.display()))
}
